import { flakeBlends, metallicColors, products, siteConfig, solidColors } from "@/data/mockData";
import { getCategoryName, getProduct, getProductSpecs } from "@/lib/catalog";
import { buildPdf, type PdfBlock } from "@/lib/pdf";
import type { Product, ResourceDoc } from "@/types";

const PLACEHOLDER_NOTE =
  "Demo placeholder document generated by the storefront prototype. Values are illustrative - always follow the manufacturer's current technical and safety documentation.";

function tdsBlocks(p: Product): PdfBlock[] {
  const blocks: PdfBlock[] = [
    { type: "heading", text: "Product description" },
    { type: "paragraph", text: p.description },
    { type: "heading", text: "Features" },
    { type: "bullets", items: p.features },
    { type: "heading", text: "Physical properties" },
    { type: "rows", rows: getProductSpecs(p).map((s) => [s.label, s.value]) },
  ];
  if (p.application) {
    const a = p.application;
    blocks.push(
      { type: "heading", text: "Application data" },
      {
        type: "rows",
        rows: [
          ["Mix ratio", a.mixRatio],
          ["Pot life", a.potLife],
          ["Recoat window", a.recoat],
          ["Light traffic", a.lightTraffic],
          ["Full cure", a.fullCure],
          ["Application temp.", a.temperature],
          ["Coverage", `${a.coverage.sqftPerUnit} sq ft ${a.coverage.basis}`],
          ["Recommended coats", String(a.recommendedCoats)],
        ],
      },
      { type: "heading", text: "Application steps" },
      { type: "bullets", items: a.steps }
    );
  }
  blocks.push({ type: "note", text: PLACEHOLDER_NOTE });
  return blocks;
}

function sdsBlocks(p: Product): PdfBlock[] {
  const hazmat = p.specs.find((s) => s.label === "Hazmat")?.value ?? "No";
  const isHazmat = hazmat.startsWith("Yes");
  return [
    {
      type: "note",
      text: "NOT A REAL SAFETY DATA SHEET. This placeholder exists only to demonstrate the download flow. Obtain the manufacturer's official SDS before storing, handling or applying any product.",
    },
    { type: "heading", text: "Section 1 - Identification" },
    {
      type: "rows",
      rows: [
        ["Product name", p.name],
        ["SKU", p.sku],
        ["Recommended use", `${getCategoryName(p.category)} floor coating component`],
        ["Supplier", siteConfig.name],
        ["Phone", siteConfig.phone],
      ],
    },
    { type: "heading", text: "Section 2 - Hazard identification" },
    {
      type: "paragraph",
      text: isHazmat
        ? "Placeholder classification. Two-component coating products may cause skin and eye irritation and allergic skin reactions. Refer to the manufacturer's SDS for the actual GHS classification."
        : "Placeholder classification. Not expected to be classified as hazardous for transport. Refer to the manufacturer's SDS for the actual GHS classification.",
    },
    { type: "heading", text: "Section 4 - First-aid measures" },
    {
      type: "bullets",
      items: [
        "Skin: remove contaminated clothing and wash with soap and water.",
        "Eyes: rinse cautiously with water for several minutes; seek medical attention.",
        "Inhalation: move to fresh air.",
      ],
    },
    { type: "heading", text: "Section 7 - Handling and storage" },
    {
      type: "bullets",
      items: [
        "Store sealed containers between 50-90 F, out of direct sunlight.",
        "Use with adequate ventilation.",
        "Keep away from heat, sparks and open flame.",
      ],
    },
    { type: "heading", text: "Section 8 - Exposure controls / PPE" },
    { type: "bullets", items: ["Nitrile gloves", "Safety glasses with side shields", "Organic vapor respirator where ventilation is limited"] },
    { type: "heading", text: "Section 14 - Transport information" },
    { type: "rows", rows: [["Hazmat", hazmat]] },
    { type: "note", text: PLACEHOLDER_NOTE },
  ];
}

function chartBlocks(doc: ResourceDoc): PdfBlock[] {
  if (doc.id === "chart-metallic") {
    return [
      { type: "paragraph", text: doc.description },
      { type: "heading", text: "Metallic pigments" },
      { type: "rows", rows: metallicColors.map((c) => [c.name, c.hex]) },
      { type: "note", text: "Screen and print colors are approximations. Order a physical metallic chart for accurate matching." },
    ];
  }
  if (doc.id === "chart-flake-blends") {
    return [
      { type: "paragraph", text: doc.description },
      { type: "heading", text: "Flake blends" },
      { type: "rows", rows: flakeBlends.map((b) => [b.name, `${b.description} Chips: ${b.chips.join(", ")}`]) },
      { type: "note", text: "Order a flake sample board set for accurate color matching." },
    ];
  }
  return [
    { type: "paragraph", text: doc.description },
    { type: "heading", text: "Solid colors" },
    { type: "rows", rows: solidColors.map((c) => [c.name, c.hex]) },
    { type: "note", text: "Screen and print colors are approximations. Request a physical sample for accurate matching." },
  ];
}

function guideBlocks(doc: ResourceDoc): PdfBlock[] {
  const related = products.filter((p) => p.application && (!doc.category || p.category === doc.category));
  if (doc.type === "Mix Guide") {
    return [
      { type: "paragraph", text: doc.description },
      { type: "heading", text: "Mix ratios & working time" },
      { type: "rows", rows: related.slice(0, 18).map((p) => [p.labelName, `${p.application!.mixRatio} - pot life ${p.application!.potLife}`]) },
      { type: "note", text: PLACEHOLDER_NOTE },
    ];
  }
  const lead = related[0];
  return [
    { type: "paragraph", text: doc.description },
    { type: "heading", text: "Sequence" },
    { type: "bullets", items: lead?.application?.steps ?? ["Prep the slab.", "Apply the system.", "Allow full cure."] },
    { type: "heading", text: "Recommended products" },
    { type: "bullets", items: related.slice(0, 6).map((p) => `${p.name} (${p.sku})`) },
    { type: "note", text: PLACEHOLDER_NOTE },
  ];
}

/** Render any resource document to PDF bytes. */
export function renderDocumentPdf(doc: ResourceDoc) {
  const product = doc.productId ? getProduct(doc.productId) : undefined;
  let blocks: PdfBlock[];
  if (product && doc.type === "TDS") blocks = tdsBlocks(product);
  else if (product && doc.type === "SDS") blocks = sdsBlocks(product);
  else if (doc.type === "Color Chart") blocks = chartBlocks(doc);
  else blocks = guideBlocks(doc);

  const typeLabel =
    doc.type === "TDS" ? "Technical Data Sheet" : doc.type === "SDS" ? "Safety Data Sheet (placeholder)" : doc.type;

  return buildPdf({
    brand: siteConfig.name,
    docType: typeLabel,
    title: product ? product.name : doc.title,
    subtitle: product ? `SKU ${product.sku}  -  Revised ${doc.updated}` : `Revised ${doc.updated}`,
    blocks,
    footer: `${siteConfig.name}  -  ${siteConfig.phone}  -  ${siteConfig.email}`,
  });
}
