import { createElement } from "react";
import {
  BadgePercent,
  BookOpen,
  Brush,
  Car,
  ClipboardList,
  Droplets,
  FileText,
  FlaskConical,
  Footprints,
  Gauge,
  GraduationCap,
  Grid3x3,
  Hammer,
  Hand,
  Handshake,
  HardHat,
  Headset,
  House,
  Layers,
  Package,
  PaintBucket,
  Paintbrush,
  Palette,
  Ruler,
  Shield,
  ShieldCheck,
  Sparkles,
  Store,
  Sun,
  Tag,
  Timer,
  Truck,
  Warehouse,
  Wrench,
  Zap,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";
import type { IconKey } from "@/types";

const icons: Record<IconKey, LucideIcon> = {
  layers: Layers,
  shield: Shield,
  "shield-check": ShieldCheck,
  droplets: Droplets,
  sparkles: Sparkles,
  palette: Palette,
  "paint-bucket": PaintBucket,
  paintbrush: Paintbrush,
  wrench: Wrench,
  hammer: Hammer,
  package: Package,
  "file-text": FileText,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  truck: Truck,
  headset: Headset,
  "badge-percent": BadgePercent,
  tag: Tag,
  car: Car,
  "hard-hat": HardHat,
  warehouse: Warehouse,
  home: House,
  flask: FlaskConical,
  sun: Sun,
  gauge: Gauge,
  ruler: Ruler,
  hand: Hand,
  footprints: Footprints,
  brush: Brush,
  grid: Grid3x3,
  store: Store,
  handshake: Handshake,
  clipboard: ClipboardList,
  timer: Timer,
  zap: Zap,
};

/** Renders a lucide icon from a data-friendly key (see IconKey). Decorative by default. */
export function Icon({ name, ...props }: { name: IconKey } & LucideProps) {
  return createElement(icons[name], { "aria-hidden": true, ...props });
}
